VENV=venv
PYTHON_PATH=../../$(VENV)/bin/python3
APP_NAME=fullsdk_core
.PHONY: all set-env run

all: set-env run

run:
	$(PYTHON_PATH) $(APP_NAME).py

set-env:
	export PYTHONPATH="/home/dev/Documents/SCHC_Project/Software/LabSCHC-OpenSCHC2/openschc/src"